FROM php:8.3-apache

# Install mysqli extension
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# Install pdo_mysql extension
RUN docker-php-ext-install pdo_mysql

# Update and upgrade packages
RUN apt-get update && apt-get upgrade -y
